/* DO NOT EDIT - This file generated automatically by gl_offsets.py (from Mesa) script */

/*
 * Copyright (C) 1999-2001  Brian Paul   All Rights Reserved.
 * (C) Copyright IBM Corporation 2004
 * All Rights Reserved.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sub license,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.  IN NO EVENT SHALL
 * BRIAN PAUL, IBM,
 * AND/OR THEIR SUPPLIERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
 * OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#if !defined( _GLAPI_OFFSETS_H_ )
#  define _GLAPI_OFFSETS_H_

#define _gloffset_NewList 0
#define _gloffset_EndList 1
#define _gloffset_CallList 2
#define _gloffset_CallLists 3
#define _gloffset_DeleteLists 4
#define _gloffset_GenLists 5
#define _gloffset_ListBase 6
#define _gloffset_Begin 7
#define _gloffset_Bitmap 8
#define _gloffset_Color3b 9
#define _gloffset_Color3bv 10
#define _gloffset_Color3d 11
#define _gloffset_Color3dv 12
#define _gloffset_Color3f 13
#define _gloffset_Color3fv 14
#define _gloffset_Color3i 15
#define _gloffset_Color3iv 16
#define _gloffset_Color3s 17
#define _gloffset_Color3sv 18
#define _gloffset_Color3ub 19
#define _gloffset_Color3ubv 20
#define _gloffset_Color3ui 21
#define _gloffset_Color3uiv 22
#define _gloffset_Color3us 23
#define _gloffset_Color3usv 24
#define _gloffset_Color4b 25
#define _gloffset_Color4bv 26
#define _gloffset_Color4d 27
#define _gloffset_Color4dv 28
#define _gloffset_Color4fv 30
#define _gloffset_Color4i 31
#define _gloffset_Color4iv 32
#define _gloffset_Color4s 33
#define _gloffset_Color4sv 34
#define _gloffset_Color4ubv 36
#define _gloffset_Color4ui 37
#define _gloffset_Color4uiv 38
#define _gloffset_Color4us 39
#define _gloffset_Color4usv 40
#define _gloffset_EdgeFlag 41
#define _gloffset_EdgeFlagv 42
#define _gloffset_End 43
#define _gloffset_Indexd 44
#define _gloffset_Indexdv 45
#define _gloffset_Indexf 46
#define _gloffset_Indexfv 47
#define _gloffset_Indexi 48
#define _gloffset_Indexiv 49
#define _gloffset_Indexs 50
#define _gloffset_Indexsv 51
#define _gloffset_Normal3b 52
#define _gloffset_Normal3bv 53
#define _gloffset_Normal3d 54
#define _gloffset_Normal3dv 55
#define _gloffset_Normal3fv 57
#define _gloffset_Normal3i 58
#define _gloffset_Normal3iv 59
#define _gloffset_Normal3s 60
#define _gloffset_Normal3sv 61
#define _gloffset_RasterPos2d 62
#define _gloffset_RasterPos2dv 63
#define _gloffset_RasterPos2f 64
#define _gloffset_RasterPos2fv 65
#define _gloffset_RasterPos2i 66
#define _gloffset_RasterPos2iv 67
#define _gloffset_RasterPos2s 68
#define _gloffset_RasterPos2sv 69
#define _gloffset_RasterPos3d 70
#define _gloffset_RasterPos3dv 71
#define _gloffset_RasterPos3f 72
#define _gloffset_RasterPos3fv 73
#define _gloffset_RasterPos3i 74
#define _gloffset_RasterPos3iv 75
#define _gloffset_RasterPos3s 76
#define _gloffset_RasterPos3sv 77
#define _gloffset_RasterPos4d 78
#define _gloffset_RasterPos4dv 79
#define _gloffset_RasterPos4f 80
#define _gloffset_RasterPos4fv 81
#define _gloffset_RasterPos4i 82
#define _gloffset_RasterPos4iv 83
#define _gloffset_RasterPos4s 84
#define _gloffset_RasterPos4sv 85
#define _gloffset_Rectd 86
#define _gloffset_Rectdv 87
#define _gloffset_Rectf 88
#define _gloffset_Rectfv 89
#define _gloffset_Recti 90
#define _gloffset_Rectiv 91
#define _gloffset_Rects 92
#define _gloffset_Rectsv 93
#define _gloffset_TexCoord1d 94
#define _gloffset_TexCoord1dv 95
#define _gloffset_TexCoord1f 96
#define _gloffset_TexCoord1fv 97
#define _gloffset_TexCoord1i 98
#define _gloffset_TexCoord1iv 99
#define _gloffset_TexCoord1s 100
#define _gloffset_TexCoord1sv 101
#define _gloffset_TexCoord2d 102
#define _gloffset_TexCoord2dv 103
#define _gloffset_TexCoord2f 104
#define _gloffset_TexCoord2fv 105
#define _gloffset_TexCoord2i 106
#define _gloffset_TexCoord2iv 107
#define _gloffset_TexCoord2s 108
#define _gloffset_TexCoord2sv 109
#define _gloffset_TexCoord3d 110
#define _gloffset_TexCoord3dv 111
#define _gloffset_TexCoord3f 112
#define _gloffset_TexCoord3fv 113
#define _gloffset_TexCoord3i 114
#define _gloffset_TexCoord3iv 115
#define _gloffset_TexCoord3s 116
#define _gloffset_TexCoord3sv 117
#define _gloffset_TexCoord4d 118
#define _gloffset_TexCoord4dv 119
#define _gloffset_TexCoord4f 120
#define _gloffset_TexCoord4fv 121
#define _gloffset_TexCoord4i 122
#define _gloffset_TexCoord4iv 123
#define _gloffset_TexCoord4s 124
#define _gloffset_TexCoord4sv 125
#define _gloffset_Vertex2d 126
#define _gloffset_Vertex2dv 127
#define _gloffset_Vertex2f 128
#define _gloffset_Vertex2fv 129
#define _gloffset_Vertex2i 130
#define _gloffset_Vertex2iv 131
#define _gloffset_Vertex2s 132
#define _gloffset_Vertex2sv 133
#define _gloffset_Vertex3d 134
#define _gloffset_Vertex3dv 135
#define _gloffset_Vertex3f 136
#define _gloffset_Vertex3fv 137
#define _gloffset_Vertex3i 138
#define _gloffset_Vertex3iv 139
#define _gloffset_Vertex3s 140
#define _gloffset_Vertex3sv 141
#define _gloffset_Vertex4d 142
#define _gloffset_Vertex4dv 143
#define _gloffset_Vertex4f 144
#define _gloffset_Vertex4fv 145
#define _gloffset_Vertex4i 146
#define _gloffset_Vertex4iv 147
#define _gloffset_Vertex4s 148
#define _gloffset_Vertex4sv 149
#define _gloffset_ClipPlane 150
#define _gloffset_ColorMaterial 151
#define _gloffset_Fogi 155
#define _gloffset_Fogiv 156
#define _gloffset_Lighti 161
#define _gloffset_Lightiv 162
#define _gloffset_LightModeli 165
#define _gloffset_LightModeliv 166
#define _gloffset_LineStipple 167
#define _gloffset_Materiali 171
#define _gloffset_Materialiv 172
#define _gloffset_PolygonMode 174
#define _gloffset_PolygonStipple 175
#define _gloffset_TexImage1D 182
#define _gloffset_TexGend 188
#define _gloffset_TexGendv 189
#define _gloffset_FeedbackBuffer 194
#define _gloffset_SelectBuffer 195
#define _gloffset_RenderMode 196
#define _gloffset_InitNames 197
#define _gloffset_LoadName 198
#define _gloffset_PassThrough 199
#define _gloffset_PopName 200
#define _gloffset_PushName 201
#define _gloffset_DrawBuffer 202
#define _gloffset_ClearAccum 204
#define _gloffset_ClearIndex 205
#define _gloffset_ClearDepth 208
#define _gloffset_IndexMask 212
#define _gloffset_Accum 213
#define _gloffset_PopAttrib 218
#define _gloffset_PushAttrib 219
#define _gloffset_Map1d 220
#define _gloffset_Map1f 221
#define _gloffset_Map2d 222
#define _gloffset_Map2f 223
#define _gloffset_MapGrid1d 224
#define _gloffset_MapGrid1f 225
#define _gloffset_MapGrid2d 226
#define _gloffset_MapGrid2f 227
#define _gloffset_EvalCoord1d 228
#define _gloffset_EvalCoord1dv 229
#define _gloffset_EvalCoord1f 230
#define _gloffset_EvalCoord1fv 231
#define _gloffset_EvalCoord2d 232
#define _gloffset_EvalCoord2dv 233
#define _gloffset_EvalCoord2f 234
#define _gloffset_EvalCoord2fv 235
#define _gloffset_EvalMesh1 236
#define _gloffset_EvalPoint1 237
#define _gloffset_EvalMesh2 238
#define _gloffset_EvalPoint2 239
#define _gloffset_PixelZoom 246
#define _gloffset_PixelTransferf 247
#define _gloffset_PixelTransferi 248
#define _gloffset_PixelStoref 249
#define _gloffset_PixelMapfv 251
#define _gloffset_PixelMapuiv 252
#define _gloffset_PixelMapusv 253
#define _gloffset_ReadBuffer 254
#define _gloffset_CopyPixels 255
#define _gloffset_DrawPixels 257
#define _gloffset_GetClipPlane 259
#define _gloffset_GetDoublev 260
#define _gloffset_GetLightiv 265
#define _gloffset_GetMapdv 266
#define _gloffset_GetMapfv 267
#define _gloffset_GetMapiv 268
#define _gloffset_GetMaterialiv 270
#define _gloffset_GetPixelMapfv 271
#define _gloffset_GetPixelMapuiv 272
#define _gloffset_GetPixelMapusv 273
#define _gloffset_GetPolygonStipple 274
#define _gloffset_GetTexGendv 278
#define _gloffset_GetTexImage 281
#define _gloffset_GetTexLevelParameterfv 284
#define _gloffset_GetTexLevelParameteriv 285
#define _gloffset_IsList 287
#define _gloffset_DepthRange 288
#define _gloffset_Frustum 289
#define _gloffset_LoadMatrixd 292
#define _gloffset_MultMatrixd 295
#define _gloffset_Ortho 296
#define _gloffset_Rotated 299
#define _gloffset_Scaled 301
#define _gloffset_Translated 303
#define _gloffset_ArrayElement 306
#define _gloffset_EdgeFlagPointer 312
#define _gloffset_IndexPointer 314
#define _gloffset_Indexub 315
#define _gloffset_Indexubv 316
#define _gloffset_InterleavedArrays 317
#define _gloffset_AreTexturesResident 322
#define _gloffset_CopyTexImage1D 323
#define _gloffset_CopyTexSubImage1D 325
#define _gloffset_PrioritizeTextures 331
#define _gloffset_TexSubImage1D 332
#define _gloffset_PopClientAttrib 334
#define _gloffset_PushClientAttrib 335
#define _gloffset_DrawRangeElements 338
#define _gloffset_ColorTable 339
#define _gloffset_ColorTableParameterfv 340
#define _gloffset_ColorTableParameteriv 341
#define _gloffset_CopyColorTable 342
#define _gloffset_GetColorTable 343
#define _gloffset_GetColorTableParameterfv 344
#define _gloffset_GetColorTableParameteriv 345
#define _gloffset_ColorSubTable 346
#define _gloffset_CopyColorSubTable 347
#define _gloffset_ConvolutionFilter1D 348
#define _gloffset_ConvolutionFilter2D 349
#define _gloffset_ConvolutionParameterf 350
#define _gloffset_ConvolutionParameterfv 351
#define _gloffset_ConvolutionParameteri 352
#define _gloffset_ConvolutionParameteriv 353
#define _gloffset_CopyConvolutionFilter1D 354
#define _gloffset_CopyConvolutionFilter2D 355
#define _gloffset_GetConvolutionFilter 356
#define _gloffset_GetConvolutionParameterfv 357
#define _gloffset_GetConvolutionParameteriv 358
#define _gloffset_GetSeparableFilter 359
#define _gloffset_SeparableFilter2D 360
#define _gloffset_GetHistogram 361
#define _gloffset_GetHistogramParameterfv 362
#define _gloffset_GetHistogramParameteriv 363
#define _gloffset_GetMinmax 364
#define _gloffset_GetMinmaxParameterfv 365
#define _gloffset_GetMinmaxParameteriv 366
#define _gloffset_Histogram 367
#define _gloffset_Minmax 368
#define _gloffset_ResetHistogram 369
#define _gloffset_ResetMinmax 370
#define _gloffset_MultiTexCoord1dARB 376
#define _gloffset_MultiTexCoord1dvARB 377
#define _gloffset_MultiTexCoord1fARB 378
#define _gloffset_MultiTexCoord1fvARB 379
#define _gloffset_MultiTexCoord1iARB 380
#define _gloffset_MultiTexCoord1ivARB 381
#define _gloffset_MultiTexCoord1sARB 382
#define _gloffset_MultiTexCoord1svARB 383
#define _gloffset_MultiTexCoord2dARB 384
#define _gloffset_MultiTexCoord2dvARB 385
#define _gloffset_MultiTexCoord2fARB 386
#define _gloffset_MultiTexCoord2fvARB 387
#define _gloffset_MultiTexCoord2iARB 388
#define _gloffset_MultiTexCoord2ivARB 389
#define _gloffset_MultiTexCoord2sARB 390
#define _gloffset_MultiTexCoord2svARB 391
#define _gloffset_MultiTexCoord3dARB 392
#define _gloffset_MultiTexCoord3dvARB 393
#define _gloffset_MultiTexCoord3fARB 394
#define _gloffset_MultiTexCoord3fvARB 395
#define _gloffset_MultiTexCoord3iARB 396
#define _gloffset_MultiTexCoord3ivARB 397
#define _gloffset_MultiTexCoord3sARB 398
#define _gloffset_MultiTexCoord3svARB 399
#define _gloffset_MultiTexCoord4dARB 400
#define _gloffset_MultiTexCoord4dvARB 401
#define _gloffset_MultiTexCoord4fvARB 403
#define _gloffset_MultiTexCoord4iARB 404
#define _gloffset_MultiTexCoord4ivARB 405
#define _gloffset_MultiTexCoord4sARB 406
#define _gloffset_MultiTexCoord4svARB 407

#if !defined(IN_DRI_DRIVER)

#define _gloffset_Color4f 29
#define _gloffset_Color4ub 35
#define _gloffset_Normal3f 56
#define _gloffset_CullFace 152
#define _gloffset_Fogf 153
#define _gloffset_Fogfv 154
#define _gloffset_FrontFace 157
#define _gloffset_Hint 158
#define _gloffset_Lightf 159
#define _gloffset_Lightfv 160
#define _gloffset_LightModelf 163
#define _gloffset_LightModelfv 164
#define _gloffset_LineWidth 168
#define _gloffset_Materialf 169
#define _gloffset_Materialfv 170
#define _gloffset_PointSize 173
#define _gloffset_Scissor 176
#define _gloffset_ShadeModel 177
#define _gloffset_TexParameterf 178
#define _gloffset_TexParameterfv 179
#define _gloffset_TexParameteri 180
#define _gloffset_TexParameteriv 181
#define _gloffset_TexImage2D 183
#define _gloffset_TexEnvf 184
#define _gloffset_TexEnvfv 185
#define _gloffset_TexEnvi 186
#define _gloffset_TexEnviv 187
#define _gloffset_TexGenfOES 190
#define _gloffset_TexGenfvOES 191
#define _gloffset_TexGeniOES 192
#define _gloffset_TexGenivOES 193
#define _gloffset_Clear 203
#define _gloffset_ClearColor 206
#define _gloffset_ClearStencil 207
#define _gloffset_StencilMask 209
#define _gloffset_ColorMask 210
#define _gloffset_DepthMask 211
#define _gloffset_Disable 214
#define _gloffset_Enable 215
#define _gloffset_Finish 216
#define _gloffset_Flush 217
#define _gloffset_AlphaFunc 240
#define _gloffset_BlendFunc 241
#define _gloffset_LogicOp 242
#define _gloffset_StencilFunc 243
#define _gloffset_StencilOp 244
#define _gloffset_DepthFunc 245
#define _gloffset_PixelStorei 250
#define _gloffset_ReadPixels 256
#define _gloffset_GetBooleanv 258
#define _gloffset_GetError 261
#define _gloffset_GetFloatv 262
#define _gloffset_GetIntegerv 263
#define _gloffset_GetLightfv 264
#define _gloffset_GetMaterialfv 269
#define _gloffset_GetString 275
#define _gloffset_GetTexEnvfv 276
#define _gloffset_GetTexEnviv 277
#define _gloffset_GetTexGenfvOES 279
#define _gloffset_GetTexGenivOES 280
#define _gloffset_GetTexParameterfv 282
#define _gloffset_GetTexParameteriv 283
#define _gloffset_IsEnabled 286
#define _gloffset_LoadIdentity 290
#define _gloffset_LoadMatrixf 291
#define _gloffset_MatrixMode 293
#define _gloffset_MultMatrixf 294
#define _gloffset_PopMatrix 297
#define _gloffset_PushMatrix 298
#define _gloffset_Rotatef 300
#define _gloffset_Scalef 302
#define _gloffset_Translatef 304
#define _gloffset_Viewport 305
#define _gloffset_BindTexture 307
#define _gloffset_ColorPointer 308
#define _gloffset_DisableClientState 309
#define _gloffset_DrawArrays 310
#define _gloffset_DrawElements 311
#define _gloffset_EnableClientState 313
#define _gloffset_NormalPointer 318
#define _gloffset_PolygonOffset 319
#define _gloffset_TexCoordPointer 320
#define _gloffset_VertexPointer 321
#define _gloffset_CopyTexImage2D 324
#define _gloffset_CopyTexSubImage2D 326
#define _gloffset_DeleteTextures 327
#define _gloffset_GenTextures 328
#define _gloffset_GetPointerv 329
#define _gloffset_IsTexture 330
#define _gloffset_TexSubImage2D 333
#define _gloffset_BlendColor 336
#define _gloffset_BlendEquationOES 337
#define _gloffset_TexImage3D 371
#define _gloffset_TexSubImage3D 372
#define _gloffset_CopyTexSubImage3D 373
#define _gloffset_ActiveTexture 374
#define _gloffset_ClientActiveTexture 375
#define _gloffset_MultiTexCoord4f 402
#define _gloffset_BlendEquationSeparateOES 408
#define _gloffset_BlendFuncSeparateOES 409
#define _gloffset_DrawTexfOES 410
#define _gloffset_DrawTexfvOES 411
#define _gloffset_DrawTexiOES 412
#define _gloffset_DrawTexivOES 413
#define _gloffset_DrawTexsOES 414
#define _gloffset_DrawTexsvOES 415
#define _gloffset_DrawTexxOES 416
#define _gloffset_DrawTexxvOES 417
#define _gloffset_BindFramebufferOES 418
#define _gloffset_BindRenderbufferOES 419
#define _gloffset_CheckFramebufferStatusOES 420
#define _gloffset_DeleteFramebuffersOES 421
#define _gloffset_DeleteRenderbuffersOES 422
#define _gloffset_FramebufferRenderbufferOES 423
#define _gloffset_FramebufferTexture2DOES 424
#define _gloffset_GenFramebuffersOES 425
#define _gloffset_GenRenderbuffersOES 426
#define _gloffset_GenerateMipmapOES 427
#define _gloffset_GetFramebufferAttachmentParameterivOES 428
#define _gloffset_GetRenderbufferParameterivOES 429
#define _gloffset_IsFramebufferOES 430
#define _gloffset_IsRenderbufferOES 431
#define _gloffset_RenderbufferStorageOES 432
#define _gloffset_PointSizePointerOES 433
#define _gloffset_QueryMatrixxOES 434
#define _gloffset_GetTexGenxvOES 435
#define _gloffset_TexGenxOES 436
#define _gloffset_TexGenxvOES 437
#define _gloffset_EGLImageTargetRenderbufferStorageOES 438
#define _gloffset_EGLImageTargetTexture2DOES 439
#define _gloffset_GetBufferPointervOES 440
#define _gloffset_MapBufferOES 441
#define _gloffset_UnmapBufferOES 442
#define _gloffset_BindVertexArrayAPPLE 443
#define _gloffset_DeleteVertexArraysAPPLE 444
#define _gloffset_GenVertexArraysAPPLE 445
#define _gloffset_IsVertexArrayAPPLE 446
#define _gloffset_CompressedTexImage2D 447
#define _gloffset_CompressedTexSubImage2D 448
#define _gloffset_SampleCoverage 449
#define _gloffset_BindBuffer 450
#define _gloffset_BufferData 451
#define _gloffset_BufferSubData 452
#define _gloffset_DeleteBuffers 453
#define _gloffset_GenBuffers 454
#define _gloffset_GetBufferParameteriv 455
#define _gloffset_IsBuffer 456
#define _gloffset_AlphaFuncx 457
#define _gloffset_ClearColorx 458
#define _gloffset_ClearDepthf 459
#define _gloffset_ClearDepthx 460
#define _gloffset_Color4x 461
#define _gloffset_DepthRangef 462
#define _gloffset_DepthRangex 463
#define _gloffset_Fogx 464
#define _gloffset_Fogxv 465
#define _gloffset_Frustumf 466
#define _gloffset_Frustumx 467
#define _gloffset_LightModelx 468
#define _gloffset_LightModelxv 469
#define _gloffset_Lightx 470
#define _gloffset_Lightxv 471
#define _gloffset_LineWidthx 472
#define _gloffset_LoadMatrixx 473
#define _gloffset_Materialx 474
#define _gloffset_Materialxv 475
#define _gloffset_MultMatrixx 476
#define _gloffset_MultiTexCoord4x 477
#define _gloffset_Normal3x 478
#define _gloffset_Orthof 479
#define _gloffset_Orthox 480
#define _gloffset_PointSizex 481
#define _gloffset_PolygonOffsetx 482
#define _gloffset_Rotatex 483
#define _gloffset_SampleCoveragex 484
#define _gloffset_Scalex 485
#define _gloffset_TexEnvx 486
#define _gloffset_TexEnvxv 487
#define _gloffset_TexParameterx 488
#define _gloffset_Translatex 489
#define _gloffset_ClipPlanef 490
#define _gloffset_ClipPlanex 491
#define _gloffset_GetClipPlanef 492
#define _gloffset_GetClipPlanex 493
#define _gloffset_GetFixedv 494
#define _gloffset_GetLightxv 495
#define _gloffset_GetMaterialxv 496
#define _gloffset_GetTexEnvxv 497
#define _gloffset_GetTexParameterxv 498
#define _gloffset_PointParameterx 499
#define _gloffset_PointParameterxv 500
#define _gloffset_TexParameterxv 501
#define _gloffset_PointParameterf 502
#define _gloffset_PointParameterfv 503
#define _gloffset_FIRST_DYNAMIC 504

#else

#define _gloffset_Color4f driDispatchRemapTable[Color4f_remap_index]
#define _gloffset_Color4ub driDispatchRemapTable[Color4ub_remap_index]
#define _gloffset_Normal3f driDispatchRemapTable[Normal3f_remap_index]
#define _gloffset_CullFace driDispatchRemapTable[CullFace_remap_index]
#define _gloffset_Fogf driDispatchRemapTable[Fogf_remap_index]
#define _gloffset_Fogfv driDispatchRemapTable[Fogfv_remap_index]
#define _gloffset_FrontFace driDispatchRemapTable[FrontFace_remap_index]
#define _gloffset_Hint driDispatchRemapTable[Hint_remap_index]
#define _gloffset_Lightf driDispatchRemapTable[Lightf_remap_index]
#define _gloffset_Lightfv driDispatchRemapTable[Lightfv_remap_index]
#define _gloffset_LightModelf driDispatchRemapTable[LightModelf_remap_index]
#define _gloffset_LightModelfv driDispatchRemapTable[LightModelfv_remap_index]
#define _gloffset_LineWidth driDispatchRemapTable[LineWidth_remap_index]
#define _gloffset_Materialf driDispatchRemapTable[Materialf_remap_index]
#define _gloffset_Materialfv driDispatchRemapTable[Materialfv_remap_index]
#define _gloffset_PointSize driDispatchRemapTable[PointSize_remap_index]
#define _gloffset_Scissor driDispatchRemapTable[Scissor_remap_index]
#define _gloffset_ShadeModel driDispatchRemapTable[ShadeModel_remap_index]
#define _gloffset_TexParameterf driDispatchRemapTable[TexParameterf_remap_index]
#define _gloffset_TexParameterfv driDispatchRemapTable[TexParameterfv_remap_index]
#define _gloffset_TexParameteri driDispatchRemapTable[TexParameteri_remap_index]
#define _gloffset_TexParameteriv driDispatchRemapTable[TexParameteriv_remap_index]
#define _gloffset_TexImage2D driDispatchRemapTable[TexImage2D_remap_index]
#define _gloffset_TexEnvf driDispatchRemapTable[TexEnvf_remap_index]
#define _gloffset_TexEnvfv driDispatchRemapTable[TexEnvfv_remap_index]
#define _gloffset_TexEnvi driDispatchRemapTable[TexEnvi_remap_index]
#define _gloffset_TexEnviv driDispatchRemapTable[TexEnviv_remap_index]
#define _gloffset_TexGenfOES driDispatchRemapTable[TexGenfOES_remap_index]
#define _gloffset_TexGenfvOES driDispatchRemapTable[TexGenfvOES_remap_index]
#define _gloffset_TexGeniOES driDispatchRemapTable[TexGeniOES_remap_index]
#define _gloffset_TexGenivOES driDispatchRemapTable[TexGenivOES_remap_index]
#define _gloffset_Clear driDispatchRemapTable[Clear_remap_index]
#define _gloffset_ClearColor driDispatchRemapTable[ClearColor_remap_index]
#define _gloffset_ClearStencil driDispatchRemapTable[ClearStencil_remap_index]
#define _gloffset_StencilMask driDispatchRemapTable[StencilMask_remap_index]
#define _gloffset_ColorMask driDispatchRemapTable[ColorMask_remap_index]
#define _gloffset_DepthMask driDispatchRemapTable[DepthMask_remap_index]
#define _gloffset_Disable driDispatchRemapTable[Disable_remap_index]
#define _gloffset_Enable driDispatchRemapTable[Enable_remap_index]
#define _gloffset_Finish driDispatchRemapTable[Finish_remap_index]
#define _gloffset_Flush driDispatchRemapTable[Flush_remap_index]
#define _gloffset_AlphaFunc driDispatchRemapTable[AlphaFunc_remap_index]
#define _gloffset_BlendFunc driDispatchRemapTable[BlendFunc_remap_index]
#define _gloffset_LogicOp driDispatchRemapTable[LogicOp_remap_index]
#define _gloffset_StencilFunc driDispatchRemapTable[StencilFunc_remap_index]
#define _gloffset_StencilOp driDispatchRemapTable[StencilOp_remap_index]
#define _gloffset_DepthFunc driDispatchRemapTable[DepthFunc_remap_index]
#define _gloffset_PixelStorei driDispatchRemapTable[PixelStorei_remap_index]
#define _gloffset_ReadPixels driDispatchRemapTable[ReadPixels_remap_index]
#define _gloffset_GetBooleanv driDispatchRemapTable[GetBooleanv_remap_index]
#define _gloffset_GetError driDispatchRemapTable[GetError_remap_index]
#define _gloffset_GetFloatv driDispatchRemapTable[GetFloatv_remap_index]
#define _gloffset_GetIntegerv driDispatchRemapTable[GetIntegerv_remap_index]
#define _gloffset_GetLightfv driDispatchRemapTable[GetLightfv_remap_index]
#define _gloffset_GetMaterialfv driDispatchRemapTable[GetMaterialfv_remap_index]
#define _gloffset_GetString driDispatchRemapTable[GetString_remap_index]
#define _gloffset_GetTexEnvfv driDispatchRemapTable[GetTexEnvfv_remap_index]
#define _gloffset_GetTexEnviv driDispatchRemapTable[GetTexEnviv_remap_index]
#define _gloffset_GetTexGenfvOES driDispatchRemapTable[GetTexGenfvOES_remap_index]
#define _gloffset_GetTexGenivOES driDispatchRemapTable[GetTexGenivOES_remap_index]
#define _gloffset_GetTexParameterfv driDispatchRemapTable[GetTexParameterfv_remap_index]
#define _gloffset_GetTexParameteriv driDispatchRemapTable[GetTexParameteriv_remap_index]
#define _gloffset_IsEnabled driDispatchRemapTable[IsEnabled_remap_index]
#define _gloffset_LoadIdentity driDispatchRemapTable[LoadIdentity_remap_index]
#define _gloffset_LoadMatrixf driDispatchRemapTable[LoadMatrixf_remap_index]
#define _gloffset_MatrixMode driDispatchRemapTable[MatrixMode_remap_index]
#define _gloffset_MultMatrixf driDispatchRemapTable[MultMatrixf_remap_index]
#define _gloffset_PopMatrix driDispatchRemapTable[PopMatrix_remap_index]
#define _gloffset_PushMatrix driDispatchRemapTable[PushMatrix_remap_index]
#define _gloffset_Rotatef driDispatchRemapTable[Rotatef_remap_index]
#define _gloffset_Scalef driDispatchRemapTable[Scalef_remap_index]
#define _gloffset_Translatef driDispatchRemapTable[Translatef_remap_index]
#define _gloffset_Viewport driDispatchRemapTable[Viewport_remap_index]
#define _gloffset_BindTexture driDispatchRemapTable[BindTexture_remap_index]
#define _gloffset_ColorPointer driDispatchRemapTable[ColorPointer_remap_index]
#define _gloffset_DisableClientState driDispatchRemapTable[DisableClientState_remap_index]
#define _gloffset_DrawArrays driDispatchRemapTable[DrawArrays_remap_index]
#define _gloffset_DrawElements driDispatchRemapTable[DrawElements_remap_index]
#define _gloffset_EnableClientState driDispatchRemapTable[EnableClientState_remap_index]
#define _gloffset_NormalPointer driDispatchRemapTable[NormalPointer_remap_index]
#define _gloffset_PolygonOffset driDispatchRemapTable[PolygonOffset_remap_index]
#define _gloffset_TexCoordPointer driDispatchRemapTable[TexCoordPointer_remap_index]
#define _gloffset_VertexPointer driDispatchRemapTable[VertexPointer_remap_index]
#define _gloffset_CopyTexImage2D driDispatchRemapTable[CopyTexImage2D_remap_index]
#define _gloffset_CopyTexSubImage2D driDispatchRemapTable[CopyTexSubImage2D_remap_index]
#define _gloffset_DeleteTextures driDispatchRemapTable[DeleteTextures_remap_index]
#define _gloffset_GenTextures driDispatchRemapTable[GenTextures_remap_index]
#define _gloffset_GetPointerv driDispatchRemapTable[GetPointerv_remap_index]
#define _gloffset_IsTexture driDispatchRemapTable[IsTexture_remap_index]
#define _gloffset_TexSubImage2D driDispatchRemapTable[TexSubImage2D_remap_index]
#define _gloffset_BlendColor driDispatchRemapTable[BlendColor_remap_index]
#define _gloffset_BlendEquationOES driDispatchRemapTable[BlendEquationOES_remap_index]
#define _gloffset_TexImage3D driDispatchRemapTable[TexImage3D_remap_index]
#define _gloffset_TexSubImage3D driDispatchRemapTable[TexSubImage3D_remap_index]
#define _gloffset_CopyTexSubImage3D driDispatchRemapTable[CopyTexSubImage3D_remap_index]
#define _gloffset_ActiveTexture driDispatchRemapTable[ActiveTexture_remap_index]
#define _gloffset_ClientActiveTexture driDispatchRemapTable[ClientActiveTexture_remap_index]
#define _gloffset_MultiTexCoord4f driDispatchRemapTable[MultiTexCoord4f_remap_index]
#define _gloffset_BlendEquationSeparateOES driDispatchRemapTable[BlendEquationSeparateOES_remap_index]
#define _gloffset_BlendFuncSeparateOES driDispatchRemapTable[BlendFuncSeparateOES_remap_index]
#define _gloffset_DrawTexfOES driDispatchRemapTable[DrawTexfOES_remap_index]
#define _gloffset_DrawTexfvOES driDispatchRemapTable[DrawTexfvOES_remap_index]
#define _gloffset_DrawTexiOES driDispatchRemapTable[DrawTexiOES_remap_index]
#define _gloffset_DrawTexivOES driDispatchRemapTable[DrawTexivOES_remap_index]
#define _gloffset_DrawTexsOES driDispatchRemapTable[DrawTexsOES_remap_index]
#define _gloffset_DrawTexsvOES driDispatchRemapTable[DrawTexsvOES_remap_index]
#define _gloffset_DrawTexxOES driDispatchRemapTable[DrawTexxOES_remap_index]
#define _gloffset_DrawTexxvOES driDispatchRemapTable[DrawTexxvOES_remap_index]
#define _gloffset_BindFramebufferOES driDispatchRemapTable[BindFramebufferOES_remap_index]
#define _gloffset_BindRenderbufferOES driDispatchRemapTable[BindRenderbufferOES_remap_index]
#define _gloffset_CheckFramebufferStatusOES driDispatchRemapTable[CheckFramebufferStatusOES_remap_index]
#define _gloffset_DeleteFramebuffersOES driDispatchRemapTable[DeleteFramebuffersOES_remap_index]
#define _gloffset_DeleteRenderbuffersOES driDispatchRemapTable[DeleteRenderbuffersOES_remap_index]
#define _gloffset_FramebufferRenderbufferOES driDispatchRemapTable[FramebufferRenderbufferOES_remap_index]
#define _gloffset_FramebufferTexture2DOES driDispatchRemapTable[FramebufferTexture2DOES_remap_index]
#define _gloffset_GenFramebuffersOES driDispatchRemapTable[GenFramebuffersOES_remap_index]
#define _gloffset_GenRenderbuffersOES driDispatchRemapTable[GenRenderbuffersOES_remap_index]
#define _gloffset_GenerateMipmapOES driDispatchRemapTable[GenerateMipmapOES_remap_index]
#define _gloffset_GetFramebufferAttachmentParameterivOES driDispatchRemapTable[GetFramebufferAttachmentParameterivOES_remap_index]
#define _gloffset_GetRenderbufferParameterivOES driDispatchRemapTable[GetRenderbufferParameterivOES_remap_index]
#define _gloffset_IsFramebufferOES driDispatchRemapTable[IsFramebufferOES_remap_index]
#define _gloffset_IsRenderbufferOES driDispatchRemapTable[IsRenderbufferOES_remap_index]
#define _gloffset_RenderbufferStorageOES driDispatchRemapTable[RenderbufferStorageOES_remap_index]
#define _gloffset_PointSizePointerOES driDispatchRemapTable[PointSizePointerOES_remap_index]
#define _gloffset_QueryMatrixxOES driDispatchRemapTable[QueryMatrixxOES_remap_index]
#define _gloffset_GetTexGenxvOES driDispatchRemapTable[GetTexGenxvOES_remap_index]
#define _gloffset_TexGenxOES driDispatchRemapTable[TexGenxOES_remap_index]
#define _gloffset_TexGenxvOES driDispatchRemapTable[TexGenxvOES_remap_index]
#define _gloffset_EGLImageTargetRenderbufferStorageOES driDispatchRemapTable[EGLImageTargetRenderbufferStorageOES_remap_index]
#define _gloffset_EGLImageTargetTexture2DOES driDispatchRemapTable[EGLImageTargetTexture2DOES_remap_index]
#define _gloffset_GetBufferPointervOES driDispatchRemapTable[GetBufferPointervOES_remap_index]
#define _gloffset_MapBufferOES driDispatchRemapTable[MapBufferOES_remap_index]
#define _gloffset_UnmapBufferOES driDispatchRemapTable[UnmapBufferOES_remap_index]
#define _gloffset_BindVertexArrayAPPLE driDispatchRemapTable[BindVertexArrayAPPLE_remap_index]
#define _gloffset_DeleteVertexArraysAPPLE driDispatchRemapTable[DeleteVertexArraysAPPLE_remap_index]
#define _gloffset_GenVertexArraysAPPLE driDispatchRemapTable[GenVertexArraysAPPLE_remap_index]
#define _gloffset_IsVertexArrayAPPLE driDispatchRemapTable[IsVertexArrayAPPLE_remap_index]
#define _gloffset_CompressedTexImage2D driDispatchRemapTable[CompressedTexImage2D_remap_index]
#define _gloffset_CompressedTexSubImage2D driDispatchRemapTable[CompressedTexSubImage2D_remap_index]
#define _gloffset_SampleCoverage driDispatchRemapTable[SampleCoverage_remap_index]
#define _gloffset_BindBuffer driDispatchRemapTable[BindBuffer_remap_index]
#define _gloffset_BufferData driDispatchRemapTable[BufferData_remap_index]
#define _gloffset_BufferSubData driDispatchRemapTable[BufferSubData_remap_index]
#define _gloffset_DeleteBuffers driDispatchRemapTable[DeleteBuffers_remap_index]
#define _gloffset_GenBuffers driDispatchRemapTable[GenBuffers_remap_index]
#define _gloffset_GetBufferParameteriv driDispatchRemapTable[GetBufferParameteriv_remap_index]
#define _gloffset_IsBuffer driDispatchRemapTable[IsBuffer_remap_index]
#define _gloffset_AlphaFuncx driDispatchRemapTable[AlphaFuncx_remap_index]
#define _gloffset_ClearColorx driDispatchRemapTable[ClearColorx_remap_index]
#define _gloffset_ClearDepthf driDispatchRemapTable[ClearDepthf_remap_index]
#define _gloffset_ClearDepthx driDispatchRemapTable[ClearDepthx_remap_index]
#define _gloffset_Color4x driDispatchRemapTable[Color4x_remap_index]
#define _gloffset_DepthRangef driDispatchRemapTable[DepthRangef_remap_index]
#define _gloffset_DepthRangex driDispatchRemapTable[DepthRangex_remap_index]
#define _gloffset_Fogx driDispatchRemapTable[Fogx_remap_index]
#define _gloffset_Fogxv driDispatchRemapTable[Fogxv_remap_index]
#define _gloffset_Frustumf driDispatchRemapTable[Frustumf_remap_index]
#define _gloffset_Frustumx driDispatchRemapTable[Frustumx_remap_index]
#define _gloffset_LightModelx driDispatchRemapTable[LightModelx_remap_index]
#define _gloffset_LightModelxv driDispatchRemapTable[LightModelxv_remap_index]
#define _gloffset_Lightx driDispatchRemapTable[Lightx_remap_index]
#define _gloffset_Lightxv driDispatchRemapTable[Lightxv_remap_index]
#define _gloffset_LineWidthx driDispatchRemapTable[LineWidthx_remap_index]
#define _gloffset_LoadMatrixx driDispatchRemapTable[LoadMatrixx_remap_index]
#define _gloffset_Materialx driDispatchRemapTable[Materialx_remap_index]
#define _gloffset_Materialxv driDispatchRemapTable[Materialxv_remap_index]
#define _gloffset_MultMatrixx driDispatchRemapTable[MultMatrixx_remap_index]
#define _gloffset_MultiTexCoord4x driDispatchRemapTable[MultiTexCoord4x_remap_index]
#define _gloffset_Normal3x driDispatchRemapTable[Normal3x_remap_index]
#define _gloffset_Orthof driDispatchRemapTable[Orthof_remap_index]
#define _gloffset_Orthox driDispatchRemapTable[Orthox_remap_index]
#define _gloffset_PointSizex driDispatchRemapTable[PointSizex_remap_index]
#define _gloffset_PolygonOffsetx driDispatchRemapTable[PolygonOffsetx_remap_index]
#define _gloffset_Rotatex driDispatchRemapTable[Rotatex_remap_index]
#define _gloffset_SampleCoveragex driDispatchRemapTable[SampleCoveragex_remap_index]
#define _gloffset_Scalex driDispatchRemapTable[Scalex_remap_index]
#define _gloffset_TexEnvx driDispatchRemapTable[TexEnvx_remap_index]
#define _gloffset_TexEnvxv driDispatchRemapTable[TexEnvxv_remap_index]
#define _gloffset_TexParameterx driDispatchRemapTable[TexParameterx_remap_index]
#define _gloffset_Translatex driDispatchRemapTable[Translatex_remap_index]
#define _gloffset_ClipPlanef driDispatchRemapTable[ClipPlanef_remap_index]
#define _gloffset_ClipPlanex driDispatchRemapTable[ClipPlanex_remap_index]
#define _gloffset_GetClipPlanef driDispatchRemapTable[GetClipPlanef_remap_index]
#define _gloffset_GetClipPlanex driDispatchRemapTable[GetClipPlanex_remap_index]
#define _gloffset_GetFixedv driDispatchRemapTable[GetFixedv_remap_index]
#define _gloffset_GetLightxv driDispatchRemapTable[GetLightxv_remap_index]
#define _gloffset_GetMaterialxv driDispatchRemapTable[GetMaterialxv_remap_index]
#define _gloffset_GetTexEnvxv driDispatchRemapTable[GetTexEnvxv_remap_index]
#define _gloffset_GetTexParameterxv driDispatchRemapTable[GetTexParameterxv_remap_index]
#define _gloffset_PointParameterx driDispatchRemapTable[PointParameterx_remap_index]
#define _gloffset_PointParameterxv driDispatchRemapTable[PointParameterxv_remap_index]
#define _gloffset_TexParameterxv driDispatchRemapTable[TexParameterxv_remap_index]
#define _gloffset_PointParameterf driDispatchRemapTable[PointParameterf_remap_index]
#define _gloffset_PointParameterfv driDispatchRemapTable[PointParameterfv_remap_index]

#endif /* !defined(IN_DRI_DRIVER) */

/* define aliases for compatibility */
#define _gloffset_TexGenf _gloffset_TexGenfOES
#define _gloffset_TexGenfv _gloffset_TexGenfvOES
#define _gloffset_TexGeni _gloffset_TexGeniOES
#define _gloffset_TexGeniv _gloffset_TexGenivOES
#define _gloffset_GetTexGenfv _gloffset_GetTexGenfvOES
#define _gloffset_GetTexGeniv _gloffset_GetTexGenivOES
#define _gloffset_BlendEquation _gloffset_BlendEquationOES
#define _gloffset_ActiveTextureARB _gloffset_ActiveTexture
#define _gloffset_ClientActiveTextureARB _gloffset_ClientActiveTexture
#define _gloffset_MultiTexCoord4fARB _gloffset_MultiTexCoord4f
#define _gloffset_AlphaFuncxOES _gloffset_AlphaFuncx
#define _gloffset_ClearColorxOES _gloffset_ClearColorx
#define _gloffset_ClearDepthfOES _gloffset_ClearDepthf
#define _gloffset_ClearDepthxOES _gloffset_ClearDepthx
#define _gloffset_Color4xOES _gloffset_Color4x
#define _gloffset_DepthRangefOES _gloffset_DepthRangef
#define _gloffset_DepthRangexOES _gloffset_DepthRangex
#define _gloffset_FogxOES _gloffset_Fogx
#define _gloffset_FogxvOES _gloffset_Fogxv
#define _gloffset_FrustumfOES _gloffset_Frustumf
#define _gloffset_FrustumxOES _gloffset_Frustumx
#define _gloffset_LightModelxOES _gloffset_LightModelx
#define _gloffset_LightModelxvOES _gloffset_LightModelxv
#define _gloffset_LightxOES _gloffset_Lightx
#define _gloffset_LightxvOES _gloffset_Lightxv
#define _gloffset_LineWidthxOES _gloffset_LineWidthx
#define _gloffset_LoadMatrixxOES _gloffset_LoadMatrixx
#define _gloffset_MaterialxOES _gloffset_Materialx
#define _gloffset_MaterialxvOES _gloffset_Materialxv
#define _gloffset_MultMatrixxOES _gloffset_MultMatrixx
#define _gloffset_MultiTexCoord4xOES _gloffset_MultiTexCoord4x
#define _gloffset_Normal3xOES _gloffset_Normal3x
#define _gloffset_OrthofOES _gloffset_Orthof
#define _gloffset_OrthoxOES _gloffset_Orthox
#define _gloffset_PointSizexOES _gloffset_PointSizex
#define _gloffset_PolygonOffsetxOES _gloffset_PolygonOffsetx
#define _gloffset_RotatexOES _gloffset_Rotatex
#define _gloffset_SampleCoveragexOES _gloffset_SampleCoveragex
#define _gloffset_ScalexOES _gloffset_Scalex
#define _gloffset_TexEnvxOES _gloffset_TexEnvx
#define _gloffset_TexEnvxvOES _gloffset_TexEnvxv
#define _gloffset_TexParameterxOES _gloffset_TexParameterx
#define _gloffset_TranslatexOES _gloffset_Translatex
#define _gloffset_ClipPlanefOES _gloffset_ClipPlanef
#define _gloffset_ClipPlanexOES _gloffset_ClipPlanex
#define _gloffset_GetClipPlanefOES _gloffset_GetClipPlanef
#define _gloffset_GetClipPlanexOES _gloffset_GetClipPlanex
#define _gloffset_GetFixedvOES _gloffset_GetFixedv
#define _gloffset_GetLightxvOES _gloffset_GetLightxv
#define _gloffset_GetMaterialxvOES _gloffset_GetMaterialxv
#define _gloffset_GetTexEnvxvOES _gloffset_GetTexEnvxv
#define _gloffset_GetTexParameterxvOES _gloffset_GetTexParameterxv
#define _gloffset_PointParameterxOES _gloffset_PointParameterx
#define _gloffset_PointParameterxvOES _gloffset_PointParameterxv
#define _gloffset_TexParameterxvOES _gloffset_TexParameterxv

#endif /* !defined( _GLAPI_OFFSETS_H_ ) */
